interval: 300
show-summary: false
show-tags: false
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 60
currency: USD
currency-summary-only: false
watchlist:
  - GME
  - SPY
  # - ^NDX
  - AMC
  - BTC-USD
  - BBBY
lots:
  - symbol: "GME"
    quantity: 1288
    unit_cost: 31.75
colors:
  text: "#ffffff"
